package main

import (
	icselect "github.com/thutasann/goops/intermediate_concepts/ic_select"
)

func main() {
	// Args_Sample()
	// Reader_Sample()
	// Custom_RoundTrip_Sample()
	// Loggin_Round_Tripper()

	// pointers.Pointer_Sample()
	// pointers.Pointer_Slice_Sample()
	// pointers.Pointer_Map_Sample()

	// Array_Slice_Sample()

	// Type_Switch_Sample()
	// Generic_Sample()
	// JSON_Parsing_Sample()

	// goroutines.GoRoutines_Sample_Two()
	// goroutines.Channel_Sample_One()
	// mutex.Mutex_Sample()
	// goroutines.WaitGroup_Sample()
	// goroutines.Wg_Mutex_Channel_Demo()

	// channelsamples.Basic_Channel_Sample()
	// channelsamples.Buffer_Channel_Sample()
	// channelsamples.Fan_In_Out_Web_Scraper_Sample()
	// channelsamples.Producer_Consumer_Sample()
	// channelsamples.Select_With_Multiple_Channels()
	// channelsamples.Worker_Pool_Pattern()

	// wgsamples.WG_Basic_Sample()
	// wgsamples.Crawling_Sample()

	// mutexsamples.Counter_Sample_Two()
	// mutexsamples.Shared_Map_Sample()

	// rwmutexsamples.Shared_Config_Sample()
	// rwmutexsamples.Stock_Trading_Sample()

	// contextsamples.Context_Fetch_Data_Sample()
	// contextsamples.Concurrency_With_Context_Sample()
	// howtousecontext.With_Background_Sample()
	// howtousecontext.With_Value_Sample()

	// howtousecomposeinterfaces.How_To_Use_Compose_Interfaces_Sample_One()
	// howtousecomposeinterfaces.Logger_Sample()
	// howtousecomposeinterfaces.Cloud_Storage_Client()
	// howtousecomposeinterfaces.Middleware_Pipeline()
	// howtousecomposeinterfaces.Reader_Writer_Sample()
	// howtousecomposeinterfaces.Middleware_Pipeline_Pattern()
	// howtousecomposeinterfaces.Payment_Processor_Sample()

	// howtousegoroutinesforaggdata.SampleOne()
	// howtousegoroutinesforaggdata.Sum_Of_Numbers()
	// howtousegoroutinesforaggdata.Word_Frequency_Counter()
	// howtousegoroutinesforaggdata.Streaming_Aggregator()
	// howtousegoroutinesforaggdata.FIFO_Pattern()
	// howtousegoroutinesforaggdata.Parallel_Map_Reduce_Sample()
	// howtousegoroutinesforaggdata.RealTime_Metrics_Agg_With_Ticker()
	// howtousegoroutinesforaggdata.Context_Aware_Aggr()

	// howtousechannels.Basic_Sample_One()
	// howtousechannels.Buffered_Vs_Unbuffered()
	// howtousechannels.Unbuffered_Channel_HandShake()
	// howtousechannels.Buffered_Channel_Decoupling()
	// howtousechannels.Non_Blocking_Send_Receive()
	// howtousechannels.Bounded_Concurrency()
	// howtousechannels.Unbuffereed_Handshake()
	// howtousechannels.Buffered_Waiting_Room()
	// bufferedvsunbuffered.Basic_Send_Receive_Sync()
	// bufferedvsunbuffered.Deadlock_If_No_Receiver()
	// bufferedvsunbuffered.Ping_Pong()
	// bufferedvsunbuffered.Fill_Buffer_Then_Block()
	// bufferedvsunbuffered.Drain_Empty_Buffer_Blocks()
	// bufferedvsunbuffered.Producer_Faster_Than_Consumer()
	// bufferedvsunbuffered.Worker_Pool_Concurrency_Limit()
	// bufferedvsunbuffered.Web_Scraping_With_Concurrency_Limit()
	// bufferedvsunbuffered.FileDownloader()
	// bufferedvsunbuffered.RateLimitedAPI()
	// bufferedvsunbuffered.Pipeline_Processing()

	// howtoslices.Slice_Anatomy()
	// howtoslices.Basic_Slicing()
	// howtoslices.Slices_Share_The_Same_Array()
	// howtoslices.Capacity_Controls_Growth()
	// howtoslices.Reslicing()
	// howtoslices.Copying_Slices()
	// howtoslices.Slice_Pagination_Sample()
	// howtoslices.Splitting_CSV_Rows()
	// howtoslices.Ring_Buffer_Chat_Messages()
	// howtoslices.Remove_Duplicates()
	// howtoslices.Chat_Message_Buffer()
	// howtoslices.Split_Work_For_Goroutines()
	// howtoslices.Insert_At_Sample()
	// howtoslices.Rotate_Slice_Sample()
	// howtoslices.Chunking_Data_Sample()
	// howtoslices.Stack_Slice_Sample()
	// howtoslices.Queue_Sample()
	// howtoslices.Filter_Transform_Sample()
	// howtoslices.Batch_Processing_Sample()

	// slicedatatsructure.Stack_Slice_DSA()
	// slicedatatsructure.Queue_Slice_DSA()
	// slicedatatsructure.Double_Ended_Queue_Slice_DSA()
	// slicedatatsructure.Priority_Queue_Slice_DSA()
	// slicedatatsructure.Ring_Buffer_Slice_DSA()
	// slicedatatsructure.Set_Slice_DSA()
	// slicedatatsructure.Map_Slice_DSA()

	// interfaces.Interface_Sample()

	// Worker_Pool_Sample()

	// syncvsasync.Sync_HTTP_Calls_Sample()
	// syncvsasync.Async_HTTP_Calls()
	// syncvsasync.Async_Worker_Sample()
	// syncvsasync.WebServer_Sync_Vs_Async()
	// syncvsasync.MircoServices_Calls()
	// syncvsasync.Image_Processing_Worker()
	// syncvsasync.Async_Chat_Server()
	// syncvsasync.Cron_Like_Scheduler()
	// syncvsasync.Await_With_Channel()
	// syncvsasync.Await_With_WG()
	// syncvsasync.Channel_Await_Idiom()
	// syncvsasync.Waiting_For_Goroutines()
	// syncvsasync.Mutex_For_Shared_Data()
	// syncvsasync.Synchronization_With_Channel()
	// syncvsasync.Once_Sample()
	// syncvsasync.Cond_Sample()
	// syncvsasync.Context_With_Timeout_HTTP()

	// icinterfaces.Printer_Interface_Sample()
	// icstructembedding.Car_Embedding()
	// icmethodsreceivers.Methods_Receivers()
	// icgoroutines.Cooking()
	// icchannels.Chef_Waiter()
	// icchannels.Challenge_Chef_Waiter()
	// icselect.Restaurant_Manager()
	// icselect.Basic_Timeout_Pattern()
	// icselect.Random_Channel_Race()
	// icselect.Non_Blocking_Send_Receive()
	// icselect.Multiple_Goroutines_Coordination()
	// icselect.Select_Context_Cancellation()
	// icselect.Worker_Pool_Select()
	// icselect.Pipeline_Sample()
	// icselect.Timeout_Retry()
	icselect.RateLimit()
}
